### ISSUE TITLE
createnewuser - Page Not Found

### ISSUE THREAD

**Issue by nasko** [q2apro/q2apro-create-new-user#1]
I've followed the steps listed in the README. However, when I try to access the /createneuser page, I get Page Not Found.

Maybe I'm missing something?

![screenshot_q2a_ls](https://user-images.githubusercontent.com/283257/38794272-31aaf6f4-415d-11e8-84c8-4c2cfd43f44f.png)

![screenshot_q2a_plugins](https://user-images.githubusercontent.com/283257/38794271-318f05b6-415d-11e8-9ec2-f8b4e244ec11.png)

![screenshot_q2a_not_found](https://user-images.githubusercontent.com/283257/38794269-3173215c-415d-11e8-9af2-eec140f897be.png)

**Comment by q2apro** [comment]
It is not `/createneuser` but `/createnewusers`
